--- # Installation options for Windows enviroments
role:
  analyst: # Installation options for Analyst Boxes, only option I have configured currently
    files:
    exes:
      - core
      - notepad-plus-plus-plus_386
    software:
      - yum-utils
      - podman
      - git
      - kate
      - geany
      - virt-manager
      - snapd
      - htop
      - dbus-x11
      - rsync
      - ntfs-3g
      - tmux
      - inkscape
      - epel-release
      - git
      - wireshark
      - wireshark-cli
